unbind -a -T root

bind -n M-r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# Copy mode
unbind -T prefix [
bind -n M-[ copy-mode

# Command mode
bind -n M-/ command-promt

# Save/load session
unbind -T prefix C-s
unbind -T prefix C-r
bind -n M-F6 run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh"
bind -n M-F7 run-shell "~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh"

set -g base-index 1
setw -g pane-base-index 1

set -g pane-border-lines double
set -g mouse on
set -s escape-time 0
set -g history-limit 2000

bind -n M-w new-window
bind -n M-c kill-pane
bind -n M-q kill-window
bind -n M-d detach
bind -n M-Q confirm-before -p "Kill entire session? (y/n)" kill-session
bind -n M-s choose-tree -Zs

# window select
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# focus panel
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# resize panel
bind -n M-Left  resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up    resize-pane -U 5
bind -n M-Down  resize-pane -D 5

# split window
bind -n M-- split-window -v # horizontal
bind -n M-= split-window -h # vertical

# plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.config/tmux/plugins/tpm/tpm'
